# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function For Predicting States using Kalman Filter
#' 
#' The function allows you input the parameter matrices of
#' the Kalman Filter and returns a matrix containing
#' predicted states/mesurements using given parameters.
#'
#' @param z    Best estimate of measurements
#' @param x    Initial state
#' @param f    Prediction matrix used to obtain next state
#' @param h    Matrix to model the signal
#' @param q    Covariance matrix to model uncertainity associated with untracked influences 
#' @param r    Covariance matrix to model uncertainity eg. sensor noise
#' @param p    Error covariance matrix of the state estimate 
#' @keywords   KalmanFilter
#' 
#' @return Updated states/measurements
NULL

kalmanFilter <- function(z, x, f, p, h, q, r) {
    .Call('KFilter_kalmanFilter', PACKAGE = 'KFilter', z, x, f, p, h, q, r)
}

